name: studio_pro_mobile_lite
description: Studio Pro Mobile Lite v1 offline para barberías.
publish_to: none
version: 1.7.0+8

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  intl: ^0.19.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  image_path: assets/icons/studio_pro_icon.png
  min_sdk_android: 21
